name: build

on:
  push:
    branches:
      - '*'         # matches every branch
      - '*/*'       # matches every branch containing a single '/'
      - '!main'   # excludes main
      - '!staging'   # excludes main
  pull_request:

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Setup prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y curl make libxml2-dev libxslt-dev libnode-dev node-gyp npm openssl xsltproc
      - name: Setup snaps
        run: |
          sudo snap install aws-cli --classic
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - name: Update submodules
        run: |
          make update-init update-modules
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Setup npm
        run: |
          npm install
      - name: Build site
        run: |
          make _site
