name: links

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  link_checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          cache-version: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Update submodules
        run: make update-init update-modules

      - name: Install frontend deps
        run: cd frontend && npm install

      - name: Build site
        run: make all

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --exclude-file .lycheeignore -- site/**/*.html
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
